version: "3.4"
services:
  movies:
    container_name: "movies"
    command: cargo watch -x 'run --bin rest-api'
    build:
      dockerfile: Dockerfile.localdevelopment
      context: .
      cache_from:
        - rust:1.42.0
    depends_on:
      - postgres
      - redis
    environment:
      - PG_URL=postgres://postgres:docker@postgres:5432/library?sslmode=disable
      - PG_POOL_SIZE=10
      - REDIS_URL=redis://redis

    networks:
      - movies-network
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - "8000:8000"

  # Middleware
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "docker"
    networks:
      - movies-network
    ports:
      - "5432:5432"

  dbmate:
    build:
      context: .
      dockerfile: Dockerfile.dbmate
    command:
      - /app/create_db.sh
    environment:
      DATABASE_URL: "postgres://postgres:docker@postgres:5432/library?sslmode=disable"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - movies-network
    volumes:
      - ./db:/app/db

  redis:
    image: redis:5.0.6-alpine
    container_name: redis_cache
    expose:
      - 6379
    networks:
      - movies-network
    ports:
      - "6379:6379"

networks:
  movies-network:
    driver: bridge
